### ISSUE TITLE
Need new release for continued builds

### ISSUE THREAD

**Issue by jlsherrill** [xprazak2/foreman-pipeline#45]
Trying to rebuild rpms for ror42 and getting an error as you can see here:  https://github.com/Katello/katello-packaging/pull/212

Here was the build in koji:
http://koji.katello.org/koji/taskinfo?taskID=456976

We need a new release of this gem in order to build (and likely some testing with foreman nightly)

**Comment by xprazak2** [comment]
New version was released and is in [katello-packaging](https://github.com/Katello/katello-packaging/pull/214). Thanks @jlsherrill!
